name: SkySlayer
version: '1.0'
main: de.stunni.Main
api-version: 1.19

commands:
  test:
    description: test command
  gm:
    description: change your gamemode
    aliases:
      - gamemode
  giveitem:
    description: give yourself an item with own name and amount
  vbucks:
    description: troll
  repair:
    description: repair an item
  help:
    description: send a help message
  setshop:
    description: set shop
  feed:
    description: feed yourself
  heal:
    description: heal yourself
  tp:
    description: teleport yourself to someone or someone to someone else
  tpall:
    description: teleport everyone to your location
  tphere:
    description: teleport someone to your location
  editsign:
    description: edit a sign
    aliases:
      - sign
      - es
      - esign
  werbung:
    description: werbe für etwas